export interface EmploymentPosition {
    company: string,
    description: string,
    endYear: number | 'Present',
    id: string,
    location: 'Remote' | 'On-site',
    responsibilities: string[],
    role: string,
    startYear: number,
    technologies: string[],
};

export const career : EmploymentPosition[] = [
    {
        company: 'Rawnet Digital Agency',
        description: "My role at Rawnet was more typical of Frontend Development than my others. While at Rawnet I worked with a wide range of clients and on numerous different tech-stacks, with a strong focus on self-guided learning & development between projects.",
        endYear: 2024,
        id: 'rawnet',
        location: 'Remote',
        responsibilities: [
            'Frontend Development',
            'Website Optimisation & Maintenance',
            'Legacy Project Support',
            'Lead UI Developer On Numerous Projects',
        ],
        role: 'UI Developer',
        startYear: 2021,
        technologies: [
            'HTML',
            'CSS',
            'JavaScript ES6',
            'SASS',
            'SCSS',
            'Tailwind CSS',
            'Handlebars',
            'Mustache',
            'Twig',
            'PHP',
            'Gulp',
            'NPM',
            'React',
            'React Native',
            'Git',
            'Github Actions',
            'YAML',
            'NodeJS',
            'VueJS',
            'Google Lighthouse',
        ],
    },{
        company: 'SNIPPR',
        description: "In 2021 I had an idea for a pair of mobile applications which I decided to pursue outside of working hours. From inception to market-ready products - I designed, developed, and tested my apps using the skills and experience I have gained across my career.",
        endYear: 2024,
        id: 'snippr',
        location: 'Remote',
        responsibilities: [
            'Frontend App Development',
            'Frontend Web Development',
            'Backend Development',
            'UX & UI Design',
            'API Development',
            'Project Scoping & Management',
            'Entrepeneurial Roles & Business Management',
        ],
        role: 'Founder & UI Engineer',
        startYear: 2021,
        technologies: [
            'HTML',
            'CSS',
            'JavaScript ES6',
            'SCSS',
            'Tailwind CSS',
            'React Native',
            'Expo',
            'NextJS',
            'React',
            'Firebase',
            'Firebase Cloud Functions',
            'Firestore',
            'ExpressJS',
            'NodeJS',
            'API Development',
            'API Design',
            'Headless CMS',
            'Adobe Creative Suite',
        ],
    },
    {
        company: 'Perfect Image IT Solutions',
        description: "I started at Perfect Image right out of University and eventually became the sole Frontend Developer at the company. I was responsible for all UI Design & Development, Graphic Design, and a number of other creative responsibilities. This was a varied role which allowed me to expand my skillset beyond just Frontend Development, though that always remained my primary focus.",
        endYear: 2021,
        id: 'perfect-image',
        location: 'On-site',
        responsibilities: [
            'Frontend Development & UI Design',
            'Backend Development (PHP)',
            'Advising Stakeholders on Frontend/Creative Direction',
            'Graphic Design (Print and Digital)',
            'Video Editing & Animation',
            'Brand Development',
        ],
        role: 'UI Engineer',
        startYear: 2016,
        technologies: [
            'HTML',
            'CSS',
            'JavaScript ES6',
            'LESS',
            'SASS',
            'SCSS',
            'Gulp',
            'Grunt',
            'NPM',
            'React',
            'PHP',
            'ASP.NET',
            'Git',
            'Gatsby',
            'Headless CMS',
            'WordPress',
            'NodeJS',
            'VueJS',
            'Google Lighthouse',
            'Azure',
            'SharePoint',
            'PowerApps',
            'Adobe Creative Suite',
        ],
    },
    {
        company: 'Atomspark',
        description: "In my second year of University I started a freelance business and began working for myself in my spare time, I continued for around 4 years before shifting focus to other pursuits. I had the chance to work with a variety of clients from solicitors and data analytics firms to heritage charities and more.",
        endYear: 2018,
        id: 'atomspark',
        location: 'Remote',
        responsibilities: [
            'Frontend Development & UI Design',
            'Backend Development (PHP)',
            'Project Management',
            'Client Relations & Project Scoping',
            'Entrepeneurial Roles & Business Management',
        ],
        role: 'Web Developer',
        startYear: 2014,
        technologies: [
            'HTML',
            'CSS',
            'JavaScript ES6',
            'SCSS',
            'Gulp',
            'NPM',
            'React',
            'PHP',
            'Git',
            'WordPress',
            'NodeJS',
            'Google Lighthouse',
            'Adobe Creative Suite',
        ],
    },
];