export interface Technology {
    name: string,
    area: {
        backend?: boolean,
        build?: boolean,
        cicd?: boolean,
        cms?: boolean,
        design?: boolean,
        frontend?: boolean,
    },
};

export const technologies : Technology[] = [
    { name: 'Adobe AfterEffects', area: { design: true } },
    { name: 'Adobe Illustrator', area: { design: true } },
    { name: 'Adobe InDesign', area: { design: true } },
    { name: 'Adobe Lightroom', area: { design: true } },
    { name: 'Adobe PhotoShop', area: { design: true } },
    { name: 'Adobe XD', area: { design: true } },
    { name: 'ASP.NET', area: { frontend: true } },
    { name: 'Azure DevOps', area: { cicd: true } },
    { name: 'Azure', area: { cicd: true } },
    { name: 'Babel', area: { build: true } },
    { name: 'Baidu Maps API', area: { frontend: true } },
    { name: 'Cloudinary API', area: { backend: true } },
    { name: 'CommonJS', area: { frontend: true, backend: true } },
    { name: 'Concrete5', area: { cms: true } },
    { name: 'Contentful', area: { cms: true } },
    { name: 'Craft CMS', area: { cms: true } },
    { name: 'CSS', area: { frontend: true } },
    { name: 'DatoCMS', area: { cms: true } },
    { name: 'Directus', area: { cms: true } },
    { name: 'Expo', area: { frontend: true } },
    { name: 'ExpressJS', area: { frontend: true, backend: true } },
    { name: 'Figma', area: { design: true } },
    { name: 'Firebase Admin SDK', area: { backend: true } },
    { name: 'Firebase Cloud Firestore', area: { backend: true } },
    { name: 'Firebase Cloud Functions', area: { backend: true } },
    { name: 'Firebase', area: { backend: true } },
    { name: 'Gatsby', area: { frontend: true } },
    { name: 'Github Actions', area: { cicd: true } },
    { name: 'Gitlab', area: { cicd: true } },
    { name: 'Google Cloud', area: { backend: true } },
    { name: 'Google Distance Matrix API', area: { backend: true } },
    { name: 'Google Identity Platform', area: { backend: true } },
    { name: 'Google Lighthouse', area: { frontend: true } },
    { name: 'Google Maps API', area: { frontend: true, backend: true } },
    { name: 'GraphQL', area: { frontend: true } },
    { name: 'Grunt', area: { build: true } },
    { name: 'Gulp', area: { build: true } },
    { name: 'Handlebars', area: { frontend: true } },
    { name: 'HTML', area: { frontend: true } },
    { name: 'InVision', area: { design: true } },
    { name: 'JavaScript ES5', area: { frontend: true, backend: true } },
    { name: 'JavaScript ES6', area: { frontend: true, backend: true } },
    { name: 'JavaScript', area: { frontend: true, backend: true } },
    { name: 'Jest', area: { frontend: true, backend: true } },
    { name: 'jQuery', area: { frontend: true } },
    { name: 'LESS', area: { frontend: true } },
    { name: 'Liquid HTML', area: { frontend: true } },
    { name: 'Loqate API', area: { frontend: true, backend: true } },
    { name: 'Lottie/Bodymovin', area: { frontend: true } },
    { name: 'MongoDB', area: { backend: true } },
    { name: 'Mustache', area: { frontend: true } },
    { name: 'NextJS', area: { frontend: true } },
    { name: 'NodeJS', area: { frontend: true, backend: true } },
    { name: 'NPM', area: { build: true } },
    { name: 'Payload', area: { cms: true } },
    { name: 'PHP', area: { frontend: true, backend: true } },
    { name: 'Railway', area: { cicd: true } },
    { name: 'React Native', area: { frontend: true } },
    { name: 'React Testing Library', area: { frontend: true } },
    { name: 'React', area: { frontend: true } },
    { name: 'Redux/Redux Toolkit', area: { frontend: true } },
    { name: 'REST APIs', area: { frontend: true, backend: true } },
    { name: 'Sanity', area: { cms: true } },
    { name: 'SASS', area: { frontend: true } },
    { name: 'SCSS', area: { frontend: true } },
    { name: 'SendGrid API', area: { backend: true } },
    { name: 'Storyblok', area: { cms: true } },
    { name: 'Strapi', area: { cms: true } },
    { name: 'Stripe API', area: { backend: true } },
    { name: 'Stripe SDK', area: { frontend: true } },
    { name: 'Styled Components', area: { frontend: true } },
    { name: 'Tailwind CSS', area: { frontend: true } },
    { name: 'Twig', area: { frontend: true, backend: true } },
    { name: 'TypeScript', area: { frontend: true, backend: true } },
    { name: 'Vercel', area: { cicd: true } },
    { name: 'Vue JS', area: { frontend: true } },
    { name: 'Webpack', area: { build: true } },
    { name: 'WordPress', area: { frontend: true, cms: true } },
    { name: 'Xamarin Forms', area: { frontend: true } },
    { name: 'YAML', area: { cicd: true } },
];